== Innspill til endringer i Produktspesifikasjon Punktsky 1.x

[cols="5,10,10,10", options="header"]
|===
|Når
|Fra hvem
|Innspill
|Tilsvar


| 04.02.2022
| Christian.Malmquist@kartverket.no
| Tabell 6 Bildematching - Nøyaktighetskrav: 

Feil i "horisontal nøyaktighet" / "minimum tetthet"

| Skrivefeil 

Løsning: fra 0,20-0,25 til 0,20-0,50

Rettet i 1.0.1

| 04.02.2022
| Andreas.Prebensen.Korsnes@kartverket.no
| Tabell 6 Bildematching - Nøyaktighetskrav: 

Jeg er ikke sikker på at kravet på systematisk avvik på bildematching med middels tetthet i produktspesifikasjonen Punktsky er stor nok for GSD 10 cm. For det kan være avvik i AT-en og i tillegg så blir det vanligvis ekstra avvik i høyde på bildematchinga. Så det kan være noen bildematchinger av GSD 10 cm som kan ha systematisk høydeavvik større enn 18 cm.

| Svar på epost 04.02.2022 

Nøyaktighetsskrankene for bildematching er alle arvet fra Lantmäteriet sin HML Höyddata (v2017). Når rammeverket for Punktsky ble satt opp hadde vi ikke gode nok erfaringstall og da Metria/Lantmäteriet har erfaring med bildematching gikk jeg for disse tallene som en start. Vi bør i løpet av 2022 vurdere faktisk nøyaktighet fra matching av Geovekstprosjekt. 

| 10.02.2022
| petter.solli@terratec.no
| Tabell 2. Luftbåren Topografisk LiDAR - Presisjon Maksimum Fotavtrykk

Ikke spesifisert hvor i scan teoretisk fotavtrykket skal beregnes

| Svar på epost 04.02.2022 

Inkludere setning i presisering som informerer om at krav til fotavtrykk skal gjelde for nadir.

Rettet i 1.0.1

| 25.03.2022
| Andreas.Prebensen.Korsnes@kartverket.no
| Kap15 - Appendix 1 - Klassekode Vannflate Skrivefeil

Skrivefeil i klassekode for vannoverflate. Skal være 9 og ikke 41. 

| Svar på epost 25.03.2022 

Rettet i 1.0.2

| 25.05.2022
| Christian.Malmquist@kartverket.no
| Kap11.1 Leveranse Punktsky

Inkludere referanse til https://www.asprs.org/wp-content/uploads/2010/12/LAS_Domain_Profile_Description_Topo-Bathy_Lidar.pdf for Bathymetric LiDAR

Inkludere krav til ..TRANSPAR i .HODE

|Lagt til i 1.0.3

| 18.10.2022
| Christian.Malmquist@kartverket.no / Ivar.Oveland@kartverket.no
| Justering skranker Fotavtrykk

Krav til fotavtrykk for kategori C / NDH endres fra 2.00 m til 0.75

Krav til fotavtrykk for kategori A / Detaljkartlegging endres fra 0.20 til 0.25

| Rettet i 1.0.3

| 03.01.2023
| Christian.Malmquist@kartverket.no 
| Justering post ALB Elv Innsjøprosjekt

MBES: 
Justering skrankeverdier MBES nøyaktighet: 
Justering krav til vertikal nøyaktighet: 
Absolutt    0.12m + 0.002*dybde
Presisjon   0.08m + 0.002*dybde

Krav til tetthet ALB omskrives fra: 

_Krav til Tetthet gjelder for 2m under vannstand ved måletidspunkt og faktisk tetthet vil reduseres ved økene måledyp. Et systems evne til å levere på gitt tetthet forutsetter gitte turbiditetsverdier og bunnrefleksjon._

Til: 

_Krav til tetthet gjelder for 2m under vannstand ved måletidspunkt og skal gjelde for hele sensorens operasjonsområde (depth range). Et systems evne til å levere bunnreturer innenfor operasjonsområde forutsetter gode turbiditetsverdier og bunnrefleksjon._


| Rettet i 1.0.3

|===
